apiVersion: v1
kind: Endpoints
metadata:
  name: external-svc
subsets:
  - addresses:
      - ip: 40.89.244.232 # Duck Duck Go's IP address
      - ip: 46.51.197.88 # Duck Duck Go's IP address
      - ip: 176.34.135.167 # Duck Duck Go's IP address    ports:
    ports:
    - port: 80
      name: web