---
apiVersion: v1
kind: Namespace
metadata:
  name: app-v1
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app-v1
spec:
  selector:
    name: app
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: first-k8s-app
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: app-v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 8080