---
apiVersion: v1
kind: Namespace
metadata:
  name: app-v2
---
apiVersion: v1
kind: Service
metadata:
  name: app-v2
  namespace: app-v2
spec:
  selector:
    name: app-v2
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  namespace: app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app-v2
  template:
    metadata:
      labels:
        name: app-v2
    spec:
      containers:
      - name: nginx-server
        image: app_version2
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-v2
  namespace: app-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: app-v2
            port:
              number: 8080