apiVersion: v1
kind: Service
metadata:
  name: lab3
spec:
  selector:
    name: lab3
  ports:
    - name: lab3a
      port: 8080
      targetPort: 3001
    - name: lab3b
      port: 80
      targetPort: 3002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lab3
  template:
    metadata:
      labels:
        name: lab3
    spec:
      serviceAccountName: deployment-strategies-challenge
      containers:
        - name: lab3a
          image: ghcr.io/learnk8s/labs-deployment-strategies:alive-first
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
        - name: lab3b
          image: ghcr.io/learnk8s/labs-deployment-strategies:alive-last
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 45
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 3002
            initialDelaySeconds: 45
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1