---
apiVersion: v1
kind: Service
metadata:
  name: perfect-twins-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort
  selector:
    name: perfect-twins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfect-twins-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: perfect-twins
  template:
    metadata:
      labels:
        name: perfect-twins
    spec:
      serviceAccountName: deployment-strategies-challenge
      containers:
      - name: twin
        image: ghcr.io/learnk8s/labs-deployment-strategies:perfect-twins
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 6
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
