---
apiVersion: v1
kind: Service
metadata:
  name: pod-ready-service
spec:
  ports:
  - port: 80
    targetPort: 6969
  type: NodePort
  selector:
    name: readiness
---
apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    name: readiness
spec:
  serviceAccountName: deployment-strategies-challenge
  containers:
  - name: c1
    image: ghcr.io/learnk8s/labs-deployment-strategies:pod-ready
    ports:
    - containerPort: 6969
    readinessProbe:
      httpGet:
        path: /health
        port: 6969
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 1