---
apiVersion: v1
kind: Namespace
metadata:
  name: app-v3
---
apiVersion: v1
kind: Service
metadata:
  name: app-v3
  namespace: app-v3
spec:
  selector:
    name: app-v3
  ports:
  - port: 8080
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v3
  namespace: app-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app-v3
  template:
    metadata:
      labels:
        name: app-v3
    spec:
      containers:
      - name: nginx-server
        image: app_version3
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-v3
  namespace: app-v3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s-is-great.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-v3
            port:
              number: 8080
  - http:
      paths:
      - path: /v3
        pathType: Prefix
        backend:
          service:
            name: app-v3
            port:
              number: 8080